# Workflow for deploying Hugo static content to GitHub Pages
name: Deploy Hugo site to Pages

on:
  # Trigger on pushes to the main branch
  push:
    branches: ["main"]

  # Allow manual triggering
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # Step 1: Checkout code from main
      - name: Checkout main branch
        uses: actions/checkout@v4

      # Step 2: Setup Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      # Step 3: Build Hugo site
      - name: Build site
        run: hugo --minify

      # Step 4: Create .nojekyll to skip Jekyll processing
      - name: Skip Jekyll
        run: touch ./public/.nojekyll

      # Step 5: Deploy to gh-pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
